<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKaHixrR\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKaHixrR/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKaHixrR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKaHixrR\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKaHixrR\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KaHixrR',
    'container.build_id' => 'b5ae2fdb',
    'container.build_time' => 1632986302,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKaHixrR');
