<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container61pYPin\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container61pYPin/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container61pYPin.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container61pYPin\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container61pYPin\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '61pYPin',
    'container.build_id' => 'f6adb247',
    'container.build_time' => 1632817670,
], __DIR__.\DIRECTORY_SEPARATOR.'Container61pYPin');
