<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQSCzBpu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQSCzBpu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQSCzBpu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQSCzBpu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQSCzBpu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QSCzBpu',
    'container.build_id' => '06e88866',
    'container.build_time' => 1632670773,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQSCzBpu');
