<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'app_test_test' => [[], ['_controller' => 'App\\Controller\\TestController::test'], [], [['text', '/asd']], [], []],
    'customer_list' => [[], ['_controller' => 'App\\Controller\\CustomerController:indexAction'], [], [['text', '/api/v1/customers']], [], []],
    'customer_create' => [[], ['_controller' => 'App\\Controller\\CustomerController:createAction'], [], [['text', '/api/v1/customers']], [], []],
    'product_list' => [[], ['_controller' => 'App\\Controller\\ProductController:indexAction'], [], [['text', '/api/v1/products']], [], []],
    'product_create' => [[], ['_controller' => 'App\\Controller\\ProductController:createAction'], [], [['text', '/api/v1/products']], [], []],
    'cart_show' => [['id'], ['_controller' => 'App\\Controller\\CartController:indexAction'], ['id' => '\\d+'], [['text', '/cart'], ['variable', '/', '\\d+', 'id'], ['text', '/api/v1/customers']], [], []],
    'cart_create' => [[], ['_controller' => 'App\\Controller\\CartController:createAction'], [], [['text', '/api/v1/customers/cart']], [], []],
    'cart_delete' => [['customerId', 'cartId'], ['_controller' => 'App\\Controller\\CartController:deleteAction'], ['customerId' => '\\d+', 'cartId' => '\\d+'], [['variable', '/', '\\d+', 'cartId'], ['text', '/cart'], ['variable', '/', '\\d+', 'customerId'], ['text', '/api/v1/customers']], [], []],
    'cart_update' => [['customerId'], ['_controller' => 'App\\Controller\\CartController:actionUpdate'], ['customerId' => '\\d+'], [['text', '/cart'], ['variable', '/', '\\d+', 'customerId'], ['text', '/api/v1/customers']], [], []],
    'product_update' => [['productId'], ['_controller' => 'App\\Controller\\ProductController:actionUpdate'], ['productId' => '\\d+'], [['variable', '/', '\\d+', 'productId'], ['text', '/api/v1/products']], [], []],
    'product_delete' => [['productId'], ['_controller' => 'App\\Controller\\ProductController:deleteAction'], ['productId' => '\\d+'], [['variable', '/', '\\d+', 'productId'], ['text', '/api/v1/products/delete']], [], []],
];
